services:
  nestjs_api_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_mysql_typeorm
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres_db

volumes:
  db-data: